// <auto-generated />
namespace E_Business.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class veriler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(veriler));
        
        string IMigrationMetadata.Id
        {
            get { return "201911251222370_veriler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
