// <auto-generated />
namespace E_Business.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class yorumlar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yorumlar));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250946593_yorumlar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
