// <auto-generated />
namespace E_Business.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class kategoriler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kategoriler));
        
        string IMigrationMetadata.Id
        {
            get { return "201911241249016_kategoriler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
